/**
 * English translations — source of truth for all UI copy.
 * Keys are grouped by feature/namespace; reuse `common.*` everywhere possible.
 * Keep keys stable; only add. Mirror every key in fr.ts.
 */
const en = {
  common: {
    appName: "HD WAKA",
    continue: "Continue",
    next: "Next",
    back: "Back",
    cancel: "Cancel",
    confirm: "Confirm",
    save: "Save",
    saveChanges: "Save Changes",
    done: "Done",
    submit: "Submit",
    skip: "Skip",
    edit: "Edit",
    delete: "Delete",
    remove: "Remove",
    add: "Add",
    apply: "Apply",
    retry: "Retry",
    close: "Close",
    ok: "OK",
    yes: "Yes",
    no: "No",
    search: "Search",
    seeAll: "See All",
    viewAll: "View All",
    loading: "Loading…",
    optional: "Optional",
    required: "Required",
    today: "Today",
    tomorrow: "Tomorrow",
    now: "Now",
    from: "From",
    to: "To",
    date: "Date",
    time: "Time",
    name: "Name",
    email: "Email",
    phone: "Phone",
    seats: "Seats",
    seat: "Seat",
    price: "Price",
    total: "Total",
    rating: "Rating",
    reviews: "Reviews",
    verified: "Verified",
    online: "Online",
    offline: "Offline",
    currency: "F",
    somethingWrong: "Something went wrong. Please try again.",
    select: "Select",
    selectDate: "Select Date",
    update: "Update",
    replace: "Replace",
    change: "Change",
    reset: "Reset",
    accept: "Accept",
    decline: "Decline",
    yesCancel: "Yes, Cancel",
    uploadImage: "Upload image",
    uploadFormatsHint: "Support Jpg, png, Pdf, Zip",
    tripsCount: "{{count}} trips",
    personsCount: "{{count}} persons",
    passengersCount: "{{count}} passengers",
    seatCount: "{{count}} Seat",
    seatsCount: "{{count}} Seats",
    seatsLeftCount: "{{count}} Seats Left",
    received: "Received",
    given: "Given",
    requests: "Requests",
    departure: "Departure",
    via: "Via",
  },

  language: {
    onboardingTitle: "Choose your language",
    onboardingSubtitle: "Select your preferred language to continue. You can change it anytime in Settings.",
    settingsTitle: "Language",
    settingsSubtitle: "Choose the language used across the app.",
    selectLabel: "Language",
    changedTo: "Language changed to {{language}}",
    continueIn: "Continue in {{language}}",
  },

  auth: {
    loginTitle: "Welcome back",
    loginSubtitle: "Glad to see you, Again!",
    signUpTitle: "Create your account",
    signUpSubtitle: "Sign up to start riding and sharing trips.",
    phoneNumber: "Phone Number",
    enterPhone: "Enter your phone number",
    emailAddress: "Email Address",
    enterEmail: "Enter your email",
    fullName: "Full Name",
    enterFullName: "Enter your full name",
    password: "Password",
    enterPassword: "Enter your password",
    login: "Log In",
    signUp: "Sign Up",
    continueWithPhone: "Continue with Phone",
    noAccount: "Don't have an account?",
    haveAccount: "Already have an account?",
    orContinueWith: "or continue with",
    agreeTerms: "By continuing, you agree to our Terms & Conditions and Privacy Policy.",
    verifyNumberTitle: "Verify your number",
    verifyNumberSubtitle: "Enter the 4-digit code we sent to {{phone}}.",
    enterOtp: "Enter verification code",
    resendCode: "Resend Code",
    resendIn: "Resend code in {{seconds}}s",
    didntReceive: "Didn't receive the code?",
    verify: "Verify",
    personalInfoTitle: "Personal Information",
    personalInfoSubtitle: "Tell us a bit about yourself.",
    dateOfBirth: "Date of Birth",
    gender: "Gender",
    selectGender: "Select gender",
    vehicleInfoTitle: "Vehicle Information",
    vehicleInfoSubtitle: "Add your vehicle details to start driving.",
    drivingLicenseTitle: "Driving License",
    drivingLicenseSubtitle: "Upload your driving license to get verified.",
    verificationInProgressTitle: "Verification in progress",
    verificationInProgressSubtitle: "We're reviewing your document. This usually takes 24-48 hours.",
    backToHome: "Back to Home",
    addProfilePicture: "Add profile picture",
    nationalId: "National ID",
    nationalIdHint: "Upload a clear photo of your valid national ID to verify your identity. (Max {{count}} images)",
    uploadNationalId: "Upload National ID",
    uploadNationalIdSubtitle: "Add a clear photo of your national ID",
    agreeTermsTapping: "By tapping on Continue you agree to our",
    termsOfService: "Terms of services",
    and: "and",
    privacyPolicyLink: "Privacy policy",
  },

  gender: {
    male: "Male",
    female: "Female",
    other: "Other",
  },

  role: {
    passenger: "Passenger",
    driver: "Driver",
    switchToPassenger: "Switch to Passenger",
    switchToDriver: "Switch to Driver",
  },

  tabs: {
    home: "Home",
    trips: "Trips",
    messages: "Messages",
    profile: "Profile",
  },

  home: {
    greeting: "Hi, {{name}}",
    whereTo: "Where are you going?",
    searchPlaceholder: "Search destination",
    fromLabel: "From",
    toLabel: "To",
    pickupLocation: "Pickup location",
    dropLocation: "Drop-off location",
    whenLabel: "When",
    passengers: "Passengers",
    findRides: "Find Rides",
    popularRoutes: "Popular Routes",
    upcomingTrip: "Upcoming Trip",
    noUpcomingTrips: "No upcoming trips",
    publishRide: "Publish a Ride",
    publishRideSubtitle: "Offer seats and share your travel costs.",
    goOnline: "Go Online",
    goOffline: "Go Offline",
    youAreOnline: "You're online",
    youAreOffline: "You're offline",
    todaysEarnings: "Today's Earnings",
    requests: "Ride Requests",
    noRequests: "No ride requests right now",
    driverGreeting: "Hey {{name}} !",
    onlineAvailable: "Online — Available",
    recentRequests: "Recent Requests",
    recentRides: "Recent Rides",
    passengersSubtitle: "How many seats do you need?",
    earnedFcfa: "Earned (FCFA)",
  },

  search: {
    title: "Available Rides",
    resultsCount: "{{count}} rides found",
    noResults: "No rides found",
    noResultsSubtitle: "Try changing your date or destination.",
    filters: "Filters",
    sortBy: "Sort by",
    departure: "Departure",
    price: "Price",
    seatsLeft: "{{count}} seats left",
    seatLeft: "{{count}} seat left",
    sortEarliest: "Earliest departure",
    sortLatest: "Latest departure",
    sortPriceLow: "Price: Low to High",
    sortPriceHigh: "Price: High to Low",
    sortRating: "Highest rated driver",
    fullyBooked: "Fully Booked",
    availability: "Availability",
    hideFullyBooked: "Hide fully booked rides",
    ridesAvailable: "{{count}} rides available",
  },

  ride: {
    detailsTitle: "Ride Details",
    route: "Route",
    pickup: "Pickup",
    dropoff: "Drop-off",
    departureTime: "Departure",
    arrivalTime: "Arrival",
    duration: "Duration",
    distance: "Distance",
    pricePerSeat: "Price per seat",
    availableSeats: "Available seats",
    driver: "Driver",
    vehicle: "Vehicle",
    preferences: "Trip Preferences",
    luggage: "Luggage",
    music: "Music",
    conversation: "Conversation",
    bookSeat: "Book Seat",
    bookNow: "Book Now",
    requestToBook: "Request to Book",
    contactDriver: "Contact Driver",
    viewProfile: "View Profile",
    routeDetails: "Route Details",
    meetingPoint: "Meeting point: Main Entrance",
    dropoffNote: "Dropoff: Near Boulevard de la Liberté",
    rulesAmenities: "Ride Rules & Amenities",
    ruleMaxBag: "Max 1 bag",
    ruleMaxBack: "Max 2 in back",
    ruleNoSmoking: "No smoking",
    ruleMusic: "Music inside",
    ruleAc: "Air conditioning",
    ruleUsb: "USB Chargers",
    coPassengers: "Co Passengers",
  },

  sos: {
    title: "Emergency SOS",
    subtitle: "Tap a service to call immediately.",
    warning:
      "Only use in a real emergency. Your live trip details and location can be shared with the responder.",
    emergencyServices: "Emergency Services",
    police: "Police",
    ambulance: "Ambulance",
    fire: "Fire & Rescue",
    call: "Call",
    callEmergency: "Call Emergency · {{number}}",
    callFailed: "Unable to start the call.",
    trustedContacts: "Trusted Contacts",
    addTrustedContact: "Add trusted contact",
    noTrustedContacts:
      "Add someone you trust for quick access during a ride.",
  },

  driverDetails: {
    title: "Driver",
    memberSince: "Member since {{date}}",
    totalTrips: "{{count}} trips",
    aboutDriver: "About",
    verifications: "Verifications",
    detailsTitle: "Driver Details",
    sinceYear: "Since {{year}}",
    ridingPreferences: "Riding Preferences",
  },

  payment: {
    title: "Payment",
    methodsTitle: "Payment Methods",
    addMethod: "Add Payment Method",
    selectMethod: "Select payment method",
    cash: "Cash",
    card: "Card",
    mobileMoney: "Mobile Money",
    fareBreakdown: "Fare Breakdown",
    baseFare: "Base fare",
    serviceFee: "Service fee",
    totalToPay: "Total to pay",
    payNow: "Pay Now",
    processingTitle: "Processing payment",
    processingSubtitle: "Please wait while we confirm your booking.",
    chooseSeats: "Choose Seats",
    payVia: "Pay Via",
    yourMobileMoneyNumber: "Your Mobile Money Number",
    payAmount: "Pay {{amount}}",
    processingWarning: "Please don't hit back or refresh",
  },

  paymentMethod: {
    title: "Payment Method",
    savedCards: "Saved Cards",
    addNewCard: "+ Add New Card",
    default: "Default",
    noCardsTitle: "No saved cards yet",
    noCardsSubtitle: "Add a card to pay quickly and securely.",
    selectCard: "Select a card to continue",
    cardHolder: "Card Holder",
    confirmPay: "Confirm & Pay {{amount}}",
    confirm: "Confirm Payment Method",
    done: "Done",
    secured: "Payments are encrypted & secure",
    setDefault: "Set as default",
    remove: "Remove",
  },

  addCard: {
    title: "Add Card",
    holderLabel: "Card Holder Name",
    holderPlaceholder: "Name on card",
    numberLabel: "Card Number",
    numberPlaceholder: "1234 5678 9012 3456",
    expiryLabel: "Expiry Date",
    expiryPlaceholder: "MM/YY",
    cvvLabel: "CVV",
    cvvPlaceholder: "123",
    setDefault: "Set as default card",
    save: "Add Card",
    cardHolderFallback: "Card Holder",
    errHolder: "Enter the card holder name",
    errNumber: "Enter a valid card number",
    errExpiry: "Enter a valid expiry date",
    errCvv: "Enter a valid CVV",
  },

  cardAdded: {
    title: "Card Added",
    subtitle: "Your card has been added successfully and is ready to use.",
    cta: "Done",
  },

  booking: {
    successTitle: "Booking Confirmed!",
    successSubtitle: "Your seat has been booked successfully.",
    bookingId: "Booking ID",
    viewTrip: "View Trip",
    backHome: "Back to Home",
    noteDriverContact: "Driver will contact you soon",
    noteArrivalUpdates: "Arrival updates enabled",
    noteTripDetails: "Trip details available in My Rides",
  },

  trips: {
    title: "My Trips",
    upcoming: "Upcoming",
    completed: "Completed",
    cancelled: "Cancelled",
    active: "Active",
    past: "Past",
    noTrips: "No trips yet",
    noTripsSubtitle: "Your trips will appear here once you book or publish a ride.",
    tripDetails: "Trip Details",
    cancelTrip: "Cancel Trip",
    cancelTripConfirm: "Are you sure you want to cancel this trip?",
    cancelTripLong: "Are you sure you want to cancel this trip? If you cancel it then this trip will no longer be available for any passenger.",
    trackTrip: "Track Trip",
    rateTrip: "Rate Trip",
    rateDriver: "Rate Driver",
    ratePassenger: "Rate Passenger",
    completeTrip: "Complete Trip",
    startTrip: "Start Trip",
    status: "Status",
    rideCancelled: "Ride Cancelled",
    rideCancelledNote: "This ride was cancelled.",
    cancelRide: "Cancel Ride",
    cancelRideTitle: "Cancel Ride?",
    cancelTripTitle: "Cancel Trip?",
    confirmCancel: "Yes, Cancel",
    cancelReasonLabel: "Reason for cancellation",
    enterReason: "Enter your reason",
    cancelledWithReason: "Cancelled · {{reason}}",
    reasonEmergency: "Emergency",
    reasonVehicleIssue: "Vehicle issue",
    reasonNoShow: "Passenger no-show",
    reasonChangePlans: "Change of plans",
    reasonOther: "Other",
  },

  tripStatus: {
    upcoming: "Upcoming",
    ongoing: "Ongoing",
    completed: "Completed",
    cancelled: "Cancelled",
    pending: "Pending",
    confirmed: "Confirmed",
    accepted: "Accepted",
    available: "Available",
    fullyBooked: "Fully Booked",
    inProgress: "In Progress",
  },

  publish: {
    title: "Publish a Ride",
    routeSection: "Route",
    leavingFrom: "Leaving from",
    goingTo: "Going to",
    addStop: "Add a stop",
    dateTimeSection: "Date & Time",
    departureDate: "Departure date",
    departureTime: "Departure time",
    seatsSection: "Seats & Price",
    availableSeats: "Available seats",
    pricePerSeat: "Price per seat",
    preferencesSection: "Preferences",
    publishNow: "Publish Ride",
    publishingTitle: "Publishing your ride",
    publishingSubtitle: "Setting things up. This will only take a moment.",
    publishedTitle: "Ride Published!",
    publishedSubtitle: "Passengers can now find and book your ride.",
    pickUp: "Pick-Up",
    drop: "Drop",
    chooseDate: "Choose Date",
    chooseTime: "Choose Time",
    chooseSeats: "Choose Seats",
    excludingDriver: "Excluding driver",
    recentRides: "Recent Rides",
    findingRoutes: "Finding the best routes…",
    routesFound: "{{count}} routes found",
    yourRoute: "Your route",
    choosePath: "Choose the best path for your ride",
    choosePickDrop: "Choose a pick-up and drop to see available routes.",
    fastest: "Fastest",
    confirmRoute: "Confirm Route",
    choosePickup: "Choose pick-up",
    chooseDrop: "Choose drop",
    yourVehicles: "Your Vehicles",
    selectVehicle: "Select the vehicle for this trip",
    addNewVehicle: "Add New Vehicle",
    ridePreferences: "Ride Preferences",
    ridePreferencesSubtitle: "Let passengers know what to expect",
    suggestedPrice: "Suggested Price",
    basedOnRates: "Based on distance and market rates",
    pricePerPassenger: "Price per passenger",
    quickSelect: "Quick Select",
    readyToGo: "Ready to go!",
    reviewDetails: "Review your ride details below",
    pricing: "Pricing",
    maxEarnings: "Max earnings",
  },

  passenger: {
    detailsTitle: "Passenger Details",
    contactPassenger: "Contact Passenger",
    pickupPoint: "Pickup point",
    dropPoint: "Drop-off point",
    seatsBooked: "{{count}} seats booked",
    passengers: "Passengers",
    confirmedPassengers: "Confirmed Passengers",
    memberSinceYear: "Since {{year}}",
    cancelPassenger: "Cancel Passenger",
    cancelPassengerTitle: "Cancel Passenger?",
    cancelPassengerConfirm: "Are you sure you want to cancel this passenger? This action cannot be undone.",
  },

  tripCompleted: {
    title: "Trip Completed",
    subtitle: "You've reached your destination.",
    earnedLabel: "You earned",
    rateNow: "Rate your experience",
    headerTitle: "Ride Confirmation",
    titleSuccess: "Trip Completed Successfully",
  },

  rating: {
    rateDriverTitle: "Rate your driver",
    ratePassengerTitle: "Rate your passenger",
    howWasTrip: "How was your trip?",
    addComment: "Add a comment",
    commentPlaceholder: "Share your experience (optional)",
    submitRating: "Submit Rating",
    ratingsTitle: "Ratings & Reviews",
    overallRating: "Overall Rating",
    basedOnReviews: "Based on {{count}} reviews",
    noReviews: "No reviews yet",
    reviewsCount: "({{count}} reviews)",
    catCommunication: "Communication",
    catPunctuality: "Punctuality",
    catBehaviour: "Behaviour",
    catCleanliness: "Cleanliness",
    shareExperience: "Share your experience",
    thanksDriver: "Thanks for rating your driver!",
    thanksPassenger: "Thanks for rating your passenger!",
    howWasRideWith: "How was your ride with {{name}}?",
    yourPassenger: "your passenger",
  },

  earnings: {
    title: "My Earnings",
    totalEarnings: "Total Earnings",
    thisWeek: "This Week",
    thisMonth: "This Month",
    totalTrips: "Total Trips",
    withdraw: "Withdraw",
    recentTrips: "Recent Trips",
    noEarnings: "No earnings yet",
    earnedFcfa: "Earned (FCFA)",
    transactions: "Transactions",
  },

  vehicle: {
    manageTitle: "Vehicle Information",
    addTitle: "Add Vehicle",
    brand: "Brand",
    selectBrand: "Select brand",
    model: "Model",
    enterModel: "Enter model",
    type: "Type",
    color: "Color",
    registration: "Registration Number",
    enterRegistration: "Enter registration number",
    year: "Year",
    addVehicle: "Add Vehicle",
    yourVehicle: "Your Vehicle",
    vehicleDetails: "Vehicle details",
    noVehicle: "No vehicle added yet",
    manufacturerModel: "Manufacturer & model",
    selectTypeTitle: "Select Vehicle Type",
    selectManufacturerTitle: "Select Manufacturer & Model",
    availableSeats: "Available Seats",
    capacity: "Vehicle capacity",
    uploadImages: "Upload Images",
    uploadImagesHint: "We require a few images of your vehicle. (Add minimum 5 images).",
    uploadVehicleImage: "Upload Vehicle Image",
    uploadVehicleImageSubtitle: "Add a clear photo of your vehicle",
    yourVehicles: "Your Vehicles",
    addNewVehicle: "Add New Vehicle",
  },

  license: {
    manageTitle: "Driving License",
    licenseNumber: "License Number",
    enterLicenseNumber: "Enter license number",
    expiryDate: "Expiry Date",
    frontPhoto: "Front of license",
    backPhoto: "Back of license",
    uploadPhoto: "Upload photo",
    uploadFront: "Upload front side",
    uploadBack: "Upload back side",
    saveLicense: "Save License",
    licenseImages: "License Images",
    imagesHint: "Upload a clear photo of your valid driver's license to verify your identity and eligibility to drive.",
    uploadLicenseImage: "Upload License Image",
    uploadLicenseImageSubtitle: "Add a clear photo of your driving license",
    supportedFormats: "Support Jpg, png, Pdf, Zip",
  },

  profile: {
    title: "Profile",
    accountSettings: "Account Settings",
    securityPrivacy: "Security & Privacy",
    editProfile: "Edit Profile",
    paymentMethods: "Payment Methods",
    notifications: "Notifications",
    ratings: "Ratings",
    vehicleInformation: "Vehicle Information",
    drivingLicense: "Driving License",
    myEarnings: "My Earnings",
    language: "Language",
    privacyPolicy: "Privacy Policy",
    termsConditions: "Terms & Conditions",
    helpSupport: "Help & Support",
    logOut: "Log Out",
    logOutConfirm: "Are you sure you want to log out from HD WAKA?",
    verifiedDriver: "Verified Driver",
    verifyGovtId: "Verify your Govt. ID",
    govtIdVerified: "Govt. ID Verified",
    phoneVerified: "Phone Number Verified",
    verifyEmail: "Verify your email",
    emailVerified: "Email Verified",
    trips: "Trips",
    earnings: "Earnings",
  },

  editProfile: {
    title: "Edit Profile",
    changePhoto: "Change Photo",
    firstName: "First Name",
    lastName: "Last Name",
    bio: "Bio",
    bioPlaceholder: "Tell others about yourself",
    aboutMe: "About Me",
    nationalId: "National ID",
    nationalIdHint: "Upload a clear photo of your valid national ID to verify your identity.",
  },

  notifications: {
    title: "Notifications",
    preferences: "Notification Preferences",
    push: "Push Notifications",
    email: "Email Notifications",
    sms: "SMS Notifications",
    empty: "No notifications yet",
    emptySubtitle: "We'll let you know when something happens.",
    markAllRead: "Mark all as read",
  },

  messages: {
    title: "Messages",
    empty: "No messages yet",
    emptySubtitle: "Your conversations with drivers and passengers will appear here.",
    typeMessage: "Type a message…",
    send: "Send",
    online: "Online",
    typing: "Typing…",
    repliesIn: "Replies in 1hr",
    passengerCount: "1 Passenger",
  },

  location: {
    searchTitle: "Search location",
    searchPlaceholder: "Search for a place",
    currentLocation: "Use current location",
    recentSearches: "Recent searches",
    chooseOnMap: "Choose on map",
    noResults: "No places found",
    pickupTitle: "Pick-up",
    dropTitle: "Drop",
    searching: "Searching locations…",
    noResultsSubtitle: "Try a different place or check your spelling.",
    whereToTitle: "Where to?",
    searchHint: "Start typing to search for an address, city or landmark.",
    loadError: "Couldn't load that location. Try again.",
    currentLocationError: "Couldn't get your current location.",
    gettingLocation: "Getting your location…",
    enableAccess: "Enable location access",
    unavailableRetry: "Location unavailable · Tap to retry",
    current: "Current location",
  },

  help: {
    title: "Help & Support",
    faq: "Frequently Asked Questions",
    contactUs: "Contact Us",
    callSupport: "Call Support",
    emailSupport: "Email Support",
    chatWithUs: "Chat with us",
    heroTitle: "How can we help?",
    quickActions: "Quick actions",
    liveChat: "Live Chat",
    faqs: "FAQs",
    reportIssue: "Report Issue",
    emailUs: "Email Us",
    contactDetails: "Contact details",
    officeHours: "Office hours",
    officeHoursValue: "Mon – Sun · 24 hours",
    stillNeedHelp: "Still need help?",
  },

  preferences: {
    luggageSmall: "Small",
    luggageMedium: "Medium",
    luggageLarge: "Large",
    musicAny: "Any",
    musicNone: "No Music",
    musicLow: "Low",
    musicMixed: "Mixed",
    conversationQuiet: "Quiet",
    conversationDepends: "Depends",
    conversationTalkative: "Talkative",
    title: "Ride Preferences",
    subtitle: "Let passengers know what to expect",
    smoking: "Smoking",
    pets: "Pets",
    womenOnly: "Women Only",
    airConditioning: "Air Conditioning",
    chargingPorts: "Charging Ports",
    allowed: "Allowed",
    notAllowed: "Not allowed",
    restricted: "Restricted",
    noRestriction: "No restriction",
    available: "Available",
    notAvailable: "Not available",
    luggageSize: "Luggage Size",
    musicPreference: "Music Preference",
    conversationLevel: "Conversation Level",
  },

  imagePicker: {
    title: "Add Photo",
    takePhoto: "Take Photo",
    chooseFromGallery: "Choose from Gallery",
    removePhoto: "Remove Photo",
    updatePhoto: "Update Photo",
    subtitle: "Choose how you'd like to set your picture",
    cropTitle: "Crop Photo",
    openCamera: "Open Camera",
    openCameraCaption: "Take a new photo",
    galleryCaption: "Pick from your library",
    permissionDenied: "Permission denied. Enable access in Settings.",
  },
};

export type TranslationSchema = typeof en;
export default en;
