/**
 * French translations — must mirror every key in en.ts.
 * Tone: clear, modern, professional French for the Cameroon market.
 */
import type { TranslationSchema } from "./en";

const fr: TranslationSchema = {
  common: {
    appName: "HD WAKA",
    continue: "Continuer",
    next: "Suivant",
    back: "Retour",
    cancel: "Annuler",
    confirm: "Confirmer",
    save: "Enregistrer",
    saveChanges: "Enregistrer les modifications",
    done: "Terminé",
    submit: "Envoyer",
    skip: "Passer",
    edit: "Modifier",
    delete: "Supprimer",
    remove: "Retirer",
    add: "Ajouter",
    apply: "Appliquer",
    retry: "Réessayer",
    close: "Fermer",
    ok: "OK",
    yes: "Oui",
    no: "Non",
    search: "Rechercher",
    seeAll: "Tout voir",
    viewAll: "Tout voir",
    loading: "Chargement…",
    optional: "Facultatif",
    required: "Obligatoire",
    today: "Aujourd'hui",
    tomorrow: "Demain",
    now: "Maintenant",
    from: "De",
    to: "À",
    date: "Date",
    time: "Heure",
    name: "Nom",
    email: "E-mail",
    phone: "Téléphone",
    seats: "Places",
    seat: "Place",
    price: "Prix",
    total: "Total",
    rating: "Note",
    reviews: "Avis",
    verified: "Vérifié",
    online: "En ligne",
    offline: "Hors ligne",
    currency: "F",
    somethingWrong: "Une erreur s'est produite. Veuillez réessayer.",
    select: "Sélectionner",
    selectDate: "Sélectionner une date",
    update: "Mettre à jour",
    replace: "Remplacer",
    change: "Modifier",
    reset: "Réinitialiser",
    accept: "Accepter",
    decline: "Refuser",
    yesCancel: "Oui, annuler",
    uploadImage: "Télécharger une image",
    uploadFormatsHint: "Formats pris en charge : Jpg, png, Pdf, Zip",
    tripsCount: "{{count}} trajets",
    personsCount: "{{count}} personnes",
    passengersCount: "{{count}} passagers",
    seatCount: "{{count}} place",
    seatsCount: "{{count}} places",
    seatsLeftCount: "{{count}} places restantes",
    received: "Reçus",
    given: "Donnés",
    requests: "Demandes",
    departure: "Départ",
    via: "Via",
  },

  language: {
    onboardingTitle: "Choisissez votre langue",
    onboardingSubtitle: "Sélectionnez votre langue préférée pour continuer. Vous pourrez la changer à tout moment dans les Paramètres.",
    settingsTitle: "Langue",
    settingsSubtitle: "Choisissez la langue utilisée dans toute l'application.",
    selectLabel: "Langue",
    changedTo: "Langue changée en {{language}}",
    continueIn: "Continuer en {{language}}",
  },

  auth: {
    loginTitle: "Bon retour",
    loginSubtitle: "Ravi de vous revoir!",
    signUpTitle: "Créez votre compte",
    signUpSubtitle: "Inscrivez-vous pour commencer à voyager et partager vos trajets.",
    phoneNumber: "Numéro de téléphone",
    enterPhone: "Saisissez votre numéro de téléphone",
    emailAddress: "Adresse e-mail",
    enterEmail: "Saisissez votre e-mail",
    fullName: "Nom complet",
    enterFullName: "Saisissez votre nom complet",
    password: "Mot de passe",
    enterPassword: "Saisissez votre mot de passe",
    login: "Se connecter",
    signUp: "S'inscrire",
    continueWithPhone: "Continuer avec le téléphone",
    noAccount: "Vous n'avez pas de compte ?",
    haveAccount: "Vous avez déjà un compte ?",
    orContinueWith: "ou continuer avec",
    agreeTerms: "En continuant, vous acceptez nos Conditions générales et notre Politique de confidentialité.",
    verifyNumberTitle: "Vérifiez votre numéro",
    verifyNumberSubtitle: "Saisissez le code à 4 chiffres envoyé au {{phone}}.",
    enterOtp: "Saisissez le code de vérification",
    resendCode: "Renvoyer le code",
    resendIn: "Renvoyer le code dans {{seconds}}s",
    didntReceive: "Vous n'avez pas reçu le code ?",
    verify: "Vérifier",
    personalInfoTitle: "Informations personnelles",
    personalInfoSubtitle: "Parlez-nous un peu de vous.",
    dateOfBirth: "Date de naissance",
    gender: "Sexe",
    selectGender: "Sélectionnez le sexe",
    vehicleInfoTitle: "Informations sur le véhicule",
    vehicleInfoSubtitle: "Ajoutez les détails de votre véhicule pour commencer à conduire.",
    drivingLicenseTitle: "Permis de conduire",
    drivingLicenseSubtitle: "Téléchargez votre permis de conduire pour être vérifié.",
    verificationInProgressTitle: "Vérification en cours",
    verificationInProgressSubtitle: "Nous examinons votre document. Cela prend généralement 24 à 48 heures.",
    backToHome: "Retour à l'accueil",
    addProfilePicture: "Ajouter une photo de profil",
    nationalId: "Carte nationale d'identité",
    nationalIdHint: "Téléchargez une photo nette de votre carte nationale d'identité valide pour vérifier votre identité. (Max {{count}} images)",
    uploadNationalId: "Télécharger la carte d'identité",
    uploadNationalIdSubtitle: "Ajoutez une photo nette de votre carte d'identité",
    agreeTermsTapping: "En appuyant sur Continuer, vous acceptez nos",
    termsOfService: "Conditions d'utilisation",
    and: "et",
    privacyPolicyLink: "Politique de confidentialité",
  },

  gender: {
    male: "Homme",
    female: "Femme",
    other: "Autre",
  },

  role: {
    passenger: "Passager",
    driver: "Conducteur",
    switchToPassenger: "Passer en mode Passager",
    switchToDriver: "Passer en mode Conducteur",
  },

  tabs: {
    home: "Accueil",
    trips: "Trajets",
    messages: "Messages",
    profile: "Profil",
  },

  home: {
    greeting: "Bonjour, {{name}}",
    whereTo: "Où allez-vous ?",
    searchPlaceholder: "Rechercher une destination",
    fromLabel: "Départ",
    toLabel: "Arrivée",
    pickupLocation: "Lieu de prise en charge",
    dropLocation: "Lieu de dépose",
    whenLabel: "Quand",
    passengers: "Passagers",
    findRides: "Trouver des trajets",
    popularRoutes: "Itinéraires populaires",
    upcomingTrip: "Trajet à venir",
    noUpcomingTrips: "Aucun trajet à venir",
    publishRide: "Publier un trajet",
    publishRideSubtitle: "Proposez des places et partagez vos frais de voyage.",
    goOnline: "Se mettre en ligne",
    goOffline: "Se mettre hors ligne",
    youAreOnline: "Vous êtes en ligne",
    youAreOffline: "Vous êtes hors ligne",
    todaysEarnings: "Gains du jour",
    requests: "Demandes de trajet",
    noRequests: "Aucune demande de trajet pour le moment",
    driverGreeting: "Salut {{name}} !",
    onlineAvailable: "En ligne — Disponible",
    recentRequests: "Demandes récentes",
    recentRides: "Trajets récents",
    passengersSubtitle: "Combien de places vous faut-il ?",
    earnedFcfa: "Gagné (FCFA)",
  },

  search: {
    title: "Trajets disponibles",
    resultsCount: "{{count}} trajets trouvés",
    noResults: "Aucun trajet trouvé",
    noResultsSubtitle: "Essayez de modifier votre date ou votre destination.",
    filters: "Filtres",
    sortBy: "Trier par",
    departure: "Départ",
    price: "Prix",
    seatsLeft: "{{count}} places restantes",
    seatLeft: "{{count}} place restante",
    sortEarliest: "Départ le plus tôt",
    sortLatest: "Départ le plus tard",
    sortPriceLow: "Prix : croissant",
    sortPriceHigh: "Prix : décroissant",
    sortRating: "Conducteur le mieux noté",
    fullyBooked: "Complet",
    availability: "Disponibilité",
    hideFullyBooked: "Masquer les trajets complets",
    ridesAvailable: "{{count}} trajets disponibles",
  },

  ride: {
    detailsTitle: "Détails du trajet",
    route: "Itinéraire",
    pickup: "Prise en charge",
    dropoff: "Dépose",
    departureTime: "Départ",
    arrivalTime: "Arrivée",
    duration: "Durée",
    distance: "Distance",
    pricePerSeat: "Prix par place",
    availableSeats: "Places disponibles",
    driver: "Conducteur",
    vehicle: "Véhicule",
    preferences: "Préférences de trajet",
    luggage: "Bagages",
    music: "Musique",
    conversation: "Conversation",
    bookSeat: "Réserver une place",
    bookNow: "Réserver",
    requestToBook: "Demander à réserver",
    contactDriver: "Contacter le conducteur",
    viewProfile: "Voir le profil",
    routeDetails: "Détails de l'itinéraire",
    meetingPoint: "Point de rencontre : Entrée principale",
    dropoffNote: "Dépose : près du Boulevard de la Liberté",
    rulesAmenities: "Règles et équipements",
    ruleMaxBag: "1 bagage max",
    ruleMaxBack: "Max 2 à l'arrière",
    ruleNoSmoking: "Non-fumeur",
    ruleMusic: "Musique à bord",
    ruleAc: "Climatisation",
    ruleUsb: "Chargeurs USB",
    coPassengers: "Co-passagers",
  },

  sos: {
    title: "SOS d'urgence",
    subtitle: "Touchez un service pour appeler immédiatement.",
    warning:
      "À utiliser uniquement en cas d'urgence réelle. Les détails de votre trajet et votre position peuvent être partagés avec les secours.",
    emergencyServices: "Services d'urgence",
    police: "Police",
    ambulance: "Ambulance",
    fire: "Pompiers",
    call: "Appeler",
    callEmergency: "Appeler les secours · {{number}}",
    callFailed: "Impossible de lancer l'appel.",
    trustedContacts: "Contacts de confiance",
    addTrustedContact: "Ajouter un contact de confiance",
    noTrustedContacts:
      "Ajoutez une personne de confiance pour un accès rapide pendant un trajet.",
  },

  driverDetails: {
    title: "Conducteur",
    memberSince: "Membre depuis {{date}}",
    totalTrips: "{{count}} trajets",
    aboutDriver: "À propos",
    verifications: "Vérifications",
    detailsTitle: "Détails du conducteur",
    sinceYear: "Depuis {{year}}",
    ridingPreferences: "Préférences de trajet",
  },

  payment: {
    title: "Paiement",
    methodsTitle: "Moyens de paiement",
    addMethod: "Ajouter un moyen de paiement",
    selectMethod: "Sélectionnez un moyen de paiement",
    cash: "Espèces",
    card: "Carte",
    mobileMoney: "Mobile Money",
    fareBreakdown: "Détail du tarif",
    baseFare: "Tarif de base",
    serviceFee: "Frais de service",
    totalToPay: "Total à payer",
    payNow: "Payer maintenant",
    processingTitle: "Traitement du paiement",
    processingSubtitle: "Veuillez patienter pendant que nous confirmons votre réservation.",
    chooseSeats: "Choisir les places",
    payVia: "Payer via",
    yourMobileMoneyNumber: "Votre numéro Mobile Money",
    payAmount: "Payer {{amount}}",
    processingWarning: "Ne revenez pas en arrière et n'actualisez pas",
  },

  paymentMethod: {
    title: "Moyen de paiement",
    savedCards: "Cartes enregistrées",
    addNewCard: "+ Ajouter une carte",
    default: "Par défaut",
    noCardsTitle: "Aucune carte enregistrée",
    noCardsSubtitle: "Ajoutez une carte pour payer rapidement et en toute sécurité.",
    selectCard: "Sélectionnez une carte pour continuer",
    cardHolder: "Titulaire",
    confirmPay: "Confirmer et payer {{amount}}",
    confirm: "Confirmer le moyen de paiement",
    done: "Terminé",
    secured: "Les paiements sont chiffrés et sécurisés",
    setDefault: "Définir par défaut",
    remove: "Supprimer",
  },

  addCard: {
    title: "Ajouter une carte",
    holderLabel: "Nom du titulaire",
    holderPlaceholder: "Nom sur la carte",
    numberLabel: "Numéro de carte",
    numberPlaceholder: "1234 5678 9012 3456",
    expiryLabel: "Date d'expiration",
    expiryPlaceholder: "MM/AA",
    cvvLabel: "CVV",
    cvvPlaceholder: "123",
    setDefault: "Définir comme carte par défaut",
    save: "Ajouter la carte",
    cardHolderFallback: "Titulaire",
    errHolder: "Saisissez le nom du titulaire",
    errNumber: "Saisissez un numéro de carte valide",
    errExpiry: "Saisissez une date d'expiration valide",
    errCvv: "Saisissez un CVV valide",
  },

  cardAdded: {
    title: "Carte ajoutée",
    subtitle: "Votre carte a été ajoutée avec succès et est prête à l'emploi.",
    cta: "Terminé",
  },

  booking: {
    successTitle: "Réservation confirmée !",
    successSubtitle: "Votre place a été réservée avec succès.",
    bookingId: "N° de réservation",
    viewTrip: "Voir le trajet",
    backHome: "Retour à l'accueil",
    noteDriverContact: "Le conducteur vous contactera bientôt",
    noteArrivalUpdates: "Notifications d'arrivée activées",
    noteTripDetails: "Détails du trajet disponibles dans Mes trajets",
  },

  trips: {
    title: "Mes trajets",
    upcoming: "À venir",
    completed: "Terminés",
    cancelled: "Annulés",
    active: "Actifs",
    past: "Passés",
    noTrips: "Aucun trajet pour le moment",
    noTripsSubtitle: "Vos trajets apparaîtront ici une fois que vous aurez réservé ou publié un trajet.",
    tripDetails: "Détails du trajet",
    cancelTrip: "Annuler le trajet",
    cancelTripConfirm: "Êtes-vous sûr de vouloir annuler ce trajet ?",
    cancelTripLong: "Êtes-vous sûr de vouloir annuler ce trajet ? Si vous l'annulez, il ne sera plus disponible pour aucun passager.",
    trackTrip: "Suivre le trajet",
    rateTrip: "Noter le trajet",
    rateDriver: "Noter le conducteur",
    ratePassenger: "Noter le passager",
    completeTrip: "Terminer le trajet",
    startTrip: "Démarrer le trajet",
    status: "Statut",
    rideCancelled: "Trajet annulé",
    rideCancelledNote: "Ce trajet a été annulé.",
    cancelRide: "Annuler le trajet",
    cancelRideTitle: "Annuler le trajet ?",
    cancelTripTitle: "Annuler le trajet ?",
    confirmCancel: "Oui, annuler",
    cancelReasonLabel: "Motif d'annulation",
    enterReason: "Saisissez votre motif",
    cancelledWithReason: "Annulé · {{reason}}",
    reasonEmergency: "Urgence",
    reasonVehicleIssue: "Problème de véhicule",
    reasonNoShow: "Passager absent",
    reasonChangePlans: "Changement de plan",
    reasonOther: "Autre",
  },

  tripStatus: {
    upcoming: "À venir",
    ongoing: "En cours",
    completed: "Terminé",
    cancelled: "Annulé",
    pending: "En attente",
    confirmed: "Confirmé",
    accepted: "Accepté",
    available: "Disponible",
    fullyBooked: "Complet",
    inProgress: "En cours",
  },

  publish: {
    title: "Publier un trajet",
    routeSection: "Itinéraire",
    leavingFrom: "Départ de",
    goingTo: "Destination",
    addStop: "Ajouter une étape",
    dateTimeSection: "Date et heure",
    departureDate: "Date de départ",
    departureTime: "Heure de départ",
    seatsSection: "Places et prix",
    availableSeats: "Places disponibles",
    pricePerSeat: "Prix par place",
    preferencesSection: "Préférences",
    publishNow: "Publier le trajet",
    publishingTitle: "Publication de votre trajet",
    publishingSubtitle: "Préparation en cours. Cela ne prendra qu'un instant.",
    publishedTitle: "Trajet publié !",
    publishedSubtitle: "Les passagers peuvent désormais trouver et réserver votre trajet.",
    pickUp: "Prise en charge",
    drop: "Dépose",
    chooseDate: "Choisir une date",
    chooseTime: "Choisir une heure",
    chooseSeats: "Choisir les places",
    excludingDriver: "Conducteur non compris",
    recentRides: "Trajets récents",
    findingRoutes: "Recherche des meilleurs itinéraires…",
    routesFound: "{{count}} itinéraires trouvés",
    yourRoute: "Votre itinéraire",
    choosePath: "Choisissez le meilleur chemin pour votre trajet",
    choosePickDrop: "Choisissez un point de départ et de dépose pour voir les itinéraires disponibles.",
    fastest: "Le plus rapide",
    confirmRoute: "Confirmer l'itinéraire",
    choosePickup: "Choisir le départ",
    chooseDrop: "Choisir la dépose",
    yourVehicles: "Vos véhicules",
    selectVehicle: "Sélectionnez le véhicule pour ce trajet",
    addNewVehicle: "Ajouter un nouveau véhicule",
    ridePreferences: "Préférences de trajet",
    ridePreferencesSubtitle: "Indiquez aux passagers à quoi s'attendre",
    suggestedPrice: "Prix suggéré",
    basedOnRates: "Basé sur la distance et les tarifs du marché",
    pricePerPassenger: "Prix par passager",
    quickSelect: "Sélection rapide",
    readyToGo: "Prêt à partir !",
    reviewDetails: "Vérifiez les détails de votre trajet ci-dessous",
    pricing: "Tarification",
    maxEarnings: "Gains maximum",
  },

  passenger: {
    detailsTitle: "Détails du passager",
    contactPassenger: "Contacter le passager",
    pickupPoint: "Point de prise en charge",
    dropPoint: "Point de dépose",
    seatsBooked: "{{count}} places réservées",
    passengers: "Passagers",
    confirmedPassengers: "Passagers confirmés",
    memberSinceYear: "Depuis {{year}}",
    cancelPassenger: "Annuler le passager",
    cancelPassengerTitle: "Annuler le passager ?",
    cancelPassengerConfirm: "Êtes-vous sûr de vouloir annuler ce passager ? Cette action est irréversible.",
  },

  tripCompleted: {
    title: "Trajet terminé",
    subtitle: "Vous êtes arrivé à destination.",
    earnedLabel: "Vous avez gagné",
    rateNow: "Évaluez votre expérience",
    headerTitle: "Confirmation du trajet",
    titleSuccess: "Trajet terminé avec succès",
  },

  rating: {
    rateDriverTitle: "Notez votre conducteur",
    ratePassengerTitle: "Notez votre passager",
    howWasTrip: "Comment s'est passé votre trajet ?",
    addComment: "Ajouter un commentaire",
    commentPlaceholder: "Partagez votre expérience (facultatif)",
    submitRating: "Envoyer la note",
    ratingsTitle: "Notes et avis",
    overallRating: "Note globale",
    basedOnReviews: "Basé sur {{count}} avis",
    noReviews: "Aucun avis pour le moment",
    reviewsCount: "({{count}} avis)",
    catCommunication: "Communication",
    catPunctuality: "Ponctualité",
    catBehaviour: "Comportement",
    catCleanliness: "Propreté",
    shareExperience: "Partagez votre expérience",
    thanksDriver: "Merci d'avoir noté votre conducteur !",
    thanksPassenger: "Merci d'avoir noté votre passager !",
    howWasRideWith: "Comment s'est passé votre trajet avec {{name}} ?",
    yourPassenger: "votre passager",
  },

  earnings: {
    title: "Mes gains",
    totalEarnings: "Gains totaux",
    thisWeek: "Cette semaine",
    thisMonth: "Ce mois-ci",
    totalTrips: "Trajets totaux",
    withdraw: "Retirer",
    recentTrips: "Trajets récents",
    noEarnings: "Aucun gain pour le moment",
    earnedFcfa: "Gagné (FCFA)",
    transactions: "Transactions",
  },

  vehicle: {
    manageTitle: "Informations sur le véhicule",
    addTitle: "Ajouter un véhicule",
    brand: "Marque",
    selectBrand: "Sélectionnez la marque",
    model: "Modèle",
    enterModel: "Saisissez le modèle",
    type: "Type",
    color: "Couleur",
    registration: "Numéro d'immatriculation",
    enterRegistration: "Saisissez le numéro d'immatriculation",
    year: "Année",
    addVehicle: "Ajouter un véhicule",
    yourVehicle: "Votre véhicule",
    vehicleDetails: "Détails du véhicule",
    noVehicle: "Aucun véhicule ajouté pour le moment",
    manufacturerModel: "Constructeur et modèle",
    selectTypeTitle: "Sélectionner le type de véhicule",
    selectManufacturerTitle: "Sélectionner le constructeur et le modèle",
    availableSeats: "Sièges disponibles",
    capacity: "Capacité du véhicule",
    uploadImages: "Télécharger des images",
    uploadImagesHint: "Nous avons besoin de quelques photos de votre véhicule. (Ajoutez au moins 5 images).",
    uploadVehicleImage: "Télécharger une photo du véhicule",
    uploadVehicleImageSubtitle: "Ajoutez une photo nette de votre véhicule",
    yourVehicles: "Vos véhicules",
    addNewVehicle: "Ajouter un nouveau véhicule",
  },

  license: {
    manageTitle: "Permis de conduire",
    licenseNumber: "Numéro de permis",
    enterLicenseNumber: "Saisissez le numéro de permis",
    expiryDate: "Date d'expiration",
    frontPhoto: "Recto du permis",
    backPhoto: "Verso du permis",
    uploadPhoto: "Télécharger une photo",
    uploadFront: "Télécharger le recto",
    uploadBack: "Télécharger le verso",
    saveLicense: "Enregistrer le permis",
    licenseImages: "Photos du permis",
    imagesHint: "Téléchargez une photo nette de votre permis de conduire valide pour vérifier votre identité et votre aptitude à conduire.",
    uploadLicenseImage: "Télécharger une photo du permis",
    uploadLicenseImageSubtitle: "Ajoutez une photo nette de votre permis de conduire",
    supportedFormats: "Formats pris en charge : Jpg, png, Pdf, Zip",
  },

  profile: {
    title: "Profil",
    accountSettings: "Paramètres du compte",
    securityPrivacy: "Sécurité et confidentialité",
    editProfile: "Modifier le profil",
    paymentMethods: "Moyens de paiement",
    notifications: "Notifications",
    ratings: "Notes",
    vehicleInformation: "Informations sur le véhicule",
    drivingLicense: "Permis de conduire",
    myEarnings: "Mes gains",
    language: "Langue",
    privacyPolicy: "Politique de confidentialité",
    termsConditions: "Conditions générales",
    helpSupport: "Aide et assistance",
    logOut: "Se déconnecter",
    logOutConfirm: "Êtes-vous sûr de vouloir vous déconnecter de HD WAKA ?",
    verifiedDriver: "Conducteur vérifié",
    verifyGovtId: "Vérifiez votre pièce d'identité",
    govtIdVerified: "Pièce d'identité vérifiée",
    phoneVerified: "Numéro de téléphone vérifié",
    verifyEmail: "Vérifiez votre e-mail",
    emailVerified: "E-mail vérifié",
    trips: "Trajets",
    earnings: "Gains",
  },

  editProfile: {
    title: "Modifier le profil",
    changePhoto: "Changer la photo",
    firstName: "Prénom",
    lastName: "Nom",
    bio: "Bio",
    bioPlaceholder: "Parlez de vous aux autres",
    aboutMe: "À propos de moi",
    nationalId: "Carte nationale d'identité",
    nationalIdHint: "Téléchargez une photo nette de votre carte nationale d'identité valide pour vérifier votre identité.",
  },

  notifications: {
    title: "Notifications",
    preferences: "Préférences de notification",
    push: "Notifications push",
    email: "Notifications par e-mail",
    sms: "Notifications par SMS",
    empty: "Aucune notification pour le moment",
    emptySubtitle: "Nous vous préviendrons lorsqu'il se passera quelque chose.",
    markAllRead: "Tout marquer comme lu",
  },

  messages: {
    title: "Messages",
    empty: "Aucun message pour le moment",
    emptySubtitle: "Vos conversations avec les conducteurs et les passagers apparaîtront ici.",
    typeMessage: "Saisissez un message…",
    send: "Envoyer",
    online: "En ligne",
    typing: "En train d'écrire…",
    repliesIn: "Répond en 1h",
    passengerCount: "1 passager",
  },

  location: {
    searchTitle: "Rechercher un lieu",
    searchPlaceholder: "Rechercher un lieu",
    currentLocation: "Utiliser la position actuelle",
    recentSearches: "Recherches récentes",
    chooseOnMap: "Choisir sur la carte",
    noResults: "Aucun lieu trouvé",
    pickupTitle: "Prise en charge",
    dropTitle: "Dépose",
    searching: "Recherche de lieux…",
    noResultsSubtitle: "Essayez un autre lieu ou vérifiez l'orthographe.",
    whereToTitle: "Où allez-vous ?",
    searchHint: "Commencez à taper pour rechercher une adresse, une ville ou un lieu.",
    loadError: "Impossible de charger ce lieu. Réessayez.",
    currentLocationError: "Impossible d'obtenir votre position actuelle.",
    gettingLocation: "Localisation en cours…",
    enableAccess: "Activer l'accès à la localisation",
    unavailableRetry: "Localisation indisponible · Appuyez pour réessayer",
    current: "Position actuelle",
  },

  help: {
    title: "Aide et assistance",
    faq: "Questions fréquentes",
    contactUs: "Nous contacter",
    callSupport: "Appeler l'assistance",
    emailSupport: "Envoyer un e-mail à l'assistance",
    chatWithUs: "Discuter avec nous",
    heroTitle: "Comment pouvons-nous vous aider ?",
    quickActions: "Actions rapides",
    liveChat: "Chat en direct",
    faqs: "FAQ",
    reportIssue: "Signaler un problème",
    emailUs: "Nous écrire",
    contactDetails: "Coordonnées",
    officeHours: "Heures d'ouverture",
    officeHoursValue: "Lun – Dim · 24 heures",
    stillNeedHelp: "Besoin d'aide supplémentaire ?",
  },

  preferences: {
    luggageSmall: "Petit",
    luggageMedium: "Moyen",
    luggageLarge: "Grand",
    musicAny: "Indifférent",
    musicNone: "Sans musique",
    musicLow: "Faible",
    musicMixed: "Variée",
    conversationQuiet: "Calme",
    conversationDepends: "Ça dépend",
    conversationTalkative: "Bavard",
    title: "Préférences de trajet",
    subtitle: "Indiquez aux passagers à quoi s'attendre",
    smoking: "Tabac",
    pets: "Animaux",
    womenOnly: "Femmes uniquement",
    airConditioning: "Climatisation",
    chargingPorts: "Ports de charge",
    allowed: "Autorisé",
    notAllowed: "Non autorisé",
    restricted: "Limité",
    noRestriction: "Aucune restriction",
    available: "Disponible",
    notAvailable: "Non disponible",
    luggageSize: "Taille des bagages",
    musicPreference: "Préférence musicale",
    conversationLevel: "Niveau de conversation",
  },

  imagePicker: {
    title: "Ajouter une photo",
    takePhoto: "Prendre une photo",
    chooseFromGallery: "Choisir dans la galerie",
    removePhoto: "Supprimer la photo",
    updatePhoto: "Modifier la photo",
    subtitle: "Choisissez comment définir votre photo",
    cropTitle: "Recadrer la photo",
    openCamera: "Ouvrir l'appareil photo",
    openCameraCaption: "Prendre une nouvelle photo",
    galleryCaption: "Choisir dans votre bibliothèque",
    permissionDenied: "Autorisation refusée. Activez l'accès dans les Réglages.",
  },
};

export default fr;
